alias kuflow-docker="docker compose up -d db-16-6 keycloak temporal minio formio vault fake-smtp-server dockerhost"
alias kuflow-vpn-live-up="wg-quick up eu-01a"
alias kuflow-vpn-live-down="wg-quick down eu-01a"
alias kuflow-vpn-sandbox-up="wg-quick up sandbox-01"
alias kuflow-vpn-sandbox-down="wg-quick down sandbox-01"
alias temporal-cli-local="docker run --rm -it -v ~/dev/kuflow/src/kuflow/etc/docker/volumes/temporal.io/etc/temporal/config/tls/worker:/etc/certs/ --entrypoint tctl --network host --env-file ~/dev/kuflow/conf/kuflow-temporal-dev-environment.env temporalio/admin-tools:1.20.0"
alias remove-testcontainers="docker stop $(docker ps -a -q --filter=label=org.testcontainers) && docker rm $(docker ps -a -q --filter=label=org.testcontainers)"
alias stop-testcontainers="docker stop $(docker ps -a -q --filter=label=org.testcontainers)"
# alias kubectl="kubecolor"
