{{- /* "chezmoi" is present as work around for https://github.com/twpayne/chezmoi/discussions/1724 */ -}}
{{- $cache := dict "chezmoi" .chezmoi -}}

{{- template "read-versions-and-revisions-cache" $cache -}}

"usr/share/keyrings/docker-archive-keyring.gpg":
  type: file
  url: "https://download.docker.com/linux/{{ .chezmoi.osRelease.id }}/gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/google-chrome-archive-keyring.gpg":
  type: file
  url: "https://dl.google.com/linux/linux_signing_key.pub"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/sublimehq-archive.gpg":
  type: file
  url: "https://download.sublimetext.com/sublimehq-pub.gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/spotify.gpg":
  type: file
  url: "https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/dbeaver.gpg":
  type: file
  url: "https://dbeaver.io/debs/dbeaver.gpg.key"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/oracle-virtualbox-2016.gpg":
  type: file
  url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/mise-archive-keyring.gpg":
  type: file
  url: "https://mise.jdx.dev/gpg-key.pub"
  filter:
    command: gpg
    args: ["--dearmor"]

{{ $dockerCredentialSecretServiceVersion := includeTemplate "get-github-latest-version" (list "docker/docker-credential-helpers" $cache) }}
"usr/bin/docker-credential-secretservice":
  type: file
  url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ $dockerCredentialSecretServiceVersion }}/docker-credential-secretservice-v{{ $dockerCredentialSecretServiceVersion }}.{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
  executable: true

{{ template "save-versions-and-revisions-cache" $cache -}}
